export const NetworkMessageType = {
  REQUEST_CURRENT_TICK_INFO: 27,
  RESPOND_CURRENT_TICK_INFO: 28,
  REQUEST_ENTITY: 31,
  RESPOND_ENTITY: 32,
  END_RESPONSE: 35,
  BROADCAST_TRANSACTION: 24,
} as const;
