export const NetworkMessageType = {
  REQUEST_CONTRACT_FUNCTION: 42,
  RESPOND_CONTRACT_FUNCTION: 43,
  REQUEST_CURRENT_TICK_INFO: 27,
  RESPOND_CURRENT_TICK_INFO: 28,
  REQUEST_ENTITY: 31,
  RESPOND_ENTITY: 32,
  END_RESPONSE: 35,
  BROADCAST_TRANSACTION: 24,
  REQUEST_SYSTEM_INFO: 46,
  RESPOND_SYSTEM_INFO: 47,
} as const;
